# Generated by Django 5.2.13 on 2026-09-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True, verbose_name='会话 ID（同时是房间名）')),
                ('task', models.TextField(blank=True, default='', verbose_name='任务描述')),
                ('participants', models.JSONField(blank=True, default=list, verbose_name='参与模型')),
                ('status', models.CharField(choices=[('active', '进行中'), ('finished', '已结束')], default='active', max_length=16, verbose_name='状态')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='最终结论')),
                ('round_index', models.PositiveIntegerField(default=0, verbose_name='当前轮次')),
                ('next_seq', models.PositiveIntegerField(default=0, verbose_name='下一个消息序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 会议室会话',
                'verbose_name_plural': 'AI 会议室会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouncilMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='会话内序号')),
                ('sender', models.CharField(max_length=64, verbose_name='发送者')),
                ('role', models.CharField(blank=True, default='', max_length=32, verbose_name='角色')),
                ('step', models.CharField(blank=True, default='', max_length=32, verbose_name='所属步骤')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='结构化附加数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='generic.councilsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AI 会议室消息',
                'verbose_name_plural': 'AI 会议室消息',
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['session', 'seq'], name='council_msg_seq_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'seq'), name='unique_session_seq')],
            },
        ),
    ]
